// ui/src/pages/login/index.vue
<script lang="ts" setup>
import { Icon } from "@iconify/vue";

definePage({
    meta: {
        layout: "blank",
        requiresNoAuth: true,
    },
});

const { t } = useI18n();

const title = computed(() => {
    return `${ t("pageTitle.login") } - ${ t("appName") }`;
});

useHead({
    title: title,
});

const customizedData = useCustomizeJson();
const logo = customizedData.logo;
const appName = computed(() => {
    return customizedData.name ?? t("appName");
});

const isMounted = ref(false);
const username = ref("");
const password = ref("");

const isLoading = ref(false);

const router = useRouter();

const isUsernameValid = computed(() => {
    return username.value.length >= 3 && !/\s/.test(username.value);
});
const isPasswordValid = computed(() => {
    return password.value.length >= 8;
});

const isFormSubmitted = ref(false);
const loginError = ref(false);

onMounted(() => {
    isMounted.value = true;
});

async function login() {
    isFormSubmitted.value = true;

    if (isUsernameValid.value && isPasswordValid.value) {
        isLoading.value = true;
        try {
            await pb.collection("users").authWithPassword(username.value, password.value);
            return router.push("/");
        } catch (err) {
            console.log(err);
            loginError.value = true;
        } finally {
            isLoading.value = false;
        }
    }
}
</script>

<template>
    <div class="flex h-dvh flex-col items-center justify-between px-5 py-10">
        <img
            :alt="appName"
            :src="logo"
            aria-hidden="true"
            class="
                max-w-[60vw] cursor-pointer transition
                hover:opacity-80
            "
            @click="() => router.push('/')"
        >

        <Transition name="scale-up">
            <div
                v-if="isMounted"
                class="
                    flex w-full flex-col items-center gap-5 text-center
                    sm:w-full
                "
            >
                <div class="w-full space-y-1">
                    <h2 class="text-xl text-balance">
                        {{ t("msg.login.welcomeTo") }} {{ appName }}
                    </h2>
                    <h3 class="text-base text-balance text-white/50">
                        {{ t("msg.login.pleaseLogin") }}
                    </h3>
                </div>

                <Transition name="slide-in">
                    <h3
                        v-if="loginError"
                        class="text-balance text-red-400"
                    >
                        {{ t("errorMsg.login.loginFailed") }}
                    </h3>
                </Transition>

                <form
                    class="flex min-w-[15vw] flex-col gap-4 text-center"
                    @submit.prevent="login"
                >
                    <input
                        v-model="username"
                        :class="(!isUsernameValid && isFormSubmitted) ? `
                            rounded-md bg-red-400/5 p-2 text-red-400 outline-[1.5px] outline-red-400/10 transition-all
                            placeholder:text-red-400/50
                            focus:outline-red-400/20
                        ` : `
                            rounded-md bg-white/5 p-2 outline-[1.5px] outline-white/10 transition-all
                            placeholder:text-white/50
                            focus:outline-white/20
                        `"
                        :placeholder="t('form.fields.username')"
                        autocomplete="username"
                        type="text"
                    >

                    <Transition name="slide-in">
                        <h3
                            v-if="!isUsernameValid && isFormSubmitted"
                            class="text-balance text-red-400"
                        >
                            {{ t("form.fields.usernameNotValid") }}
                        </h3>
                    </Transition>

                    <input
                        v-model="password"
                        :class="(!isPasswordValid && isFormSubmitted) ? `
                            rounded-md bg-red-400/5 p-2 text-red-400 outline-[1.5px] outline-red-400/10 transition-all
                            placeholder:text-red-400/50
                            focus:outline-red-400/20
                        ` : `
                            rounded-md bg-white/5 p-2 outline-[1.5px] outline-white/10 transition-all
                            placeholder:text-white/50
                            focus:outline-white/20
                        `"
                        :placeholder="t('form.fields.password')"
                        autocomplete="current-password"
                        type="password"
                    >

                    <Transition name="slide-in">
                        <h3
                            v-if="!isPasswordValid && isFormSubmitted"
                            class="text-balance text-red-400"
                        >
                            {{ t("form.fields.passwordNotValid") }}
                        </h3>
                    </Transition>

                    <button
                        :class="isLoading ? `
                            pointer-events-none flex cursor-pointer items-center justify-center gap-2 rounded-md bg-main
                            p-2 opacity-50
                        ` : `
                            flex cursor-pointer items-center justify-center gap-2 rounded-md bg-main p-2 transition
                            hover:bg-main/80
                        `"
                        type="submit"
                    >
                        <template v-if="isLoading">
                            {{ t("msg.loggingIn") }}
                            <Icon
                                class="shrink-0 animate-spin text-base"
                                icon="fluent:spinner-ios-16-regular"
                            />
                        </template>
                        <template v-else>
                            {{ t("button.login") }}
                            <Icon class="shrink-0 text-base" icon="ph:arrow-right" />
                        </template>
                    </button>
                </form>

                <button>
                    {{ t("button.alreadyLoggedIn") }}
                    <span
                        class="
                            cursor-pointer text-white underline transition
                            hover:text-white/80
                        "
                    >
                        {{ t("myCourses") }}
                    </span>
                </button>
            </div>
        </Transition>

        <p class="text-center text-balance text-white/50">
            {{
                t("copyright", {
                    fullYear: new Date().getFullYear(),
                    appName: appName,
                })
            }}
        </p>
    </div>
</template>

// ui/src/routes/Login.svelte
<script>
    import customize from "../../customize.json";
    import { onMount } from "svelte";
    import { scale, slide } from "svelte/transition";
    import { quintOut } from "svelte/easing";
    import Icon from "@iconify/svelte";
    import { pb } from "../lib/pocketbase";
    import { navigate } from "svelte-routing";
    import Title from "../components/Title.svelte";
    import { t } from "../lib/i18n";

    const {name, logo, logo_size} = customize;

    let isMounted = false;
    let username = "";
    let password = "";

    let isLoading = false;
    let isUsernameValid = false;
    let isPasswordValid = false;

    let isFormSubmitted = false;
    let loginError = false;

    $: isUsernameValid = username.length >= 3 && !/\s/.test(username);
    $: isPasswordValid = password.length >= 8;

    onMount(() => {
        isMounted = true;
    });

    function submitForm() {
        isFormSubmitted = true;
    }

    async function login() {
        submitForm();
        if (isUsernameValid && isPasswordValid) {
            isLoading = true;
            try {
                await pb.collection("users").authWithPassword(username, password);
                navigate("/");
            }
            catch (err) {
                loginError = true;
            }
            isLoading = false;
        }
    }
</script>

<Title suffix="Login" />

<main class="flex h-dvh flex-col items-center justify-between px-5 py-10">
    <img
            alt={`${name} Logo`}
            aria-hidden="true"
            class="cursor-pointer transition hover:opacity-80"
            on:click={() => navigate("/")}
            src={logo}
            style="width: {logo_size}px;"
    />
    {#if isMounted}
        <div
                transition:scale={{ duration: 500, opacity: 0.001, start: 0.98 }}
                class="flex w-[500px] flex-col gap-5 sm:w-full"
        >
            <div class="w-full space-y-1">
                <h2 class="text-balance text-xl">{$t("welcomeTo")} {name}</h2>
                <h3 class="text-balance text-base text-white/50">
                    {$t("pleaseLogin")}
                </h3>
            </div>

            {#if loginError}
                <h3
                        in:slide={{ duration: 300, easing: quintOut }}
                        class="text-balance text-red-400"
                >
                    {$t("loginFailed")}
                </h3>
            {/if}

            <form class="flex flex-col gap-4" on:submit|preventDefault>
                <input
                        bind:value={username}
                        class={!isUsernameValid && isFormSubmitted
            ? "rounded-md bg-red-400/5 p-2 text-red-400 outline outline-[1.5px] outline-red-400/10 transition-all placeholder:text-red-400/50 focus:outline-red-400/20"
            : "rounded-md bg-white/5 p-2 outline outline-[1.5px] outline-white/10 transition-all placeholder:text-white/50 focus:outline-white/20"}
                        placeholder={$t("username")}
                        type="text"
                />
                {#if !isUsernameValid && isFormSubmitted}
                    <h3
                            in:slide={{ duration: 300, easing: quintOut }}
                            class="text-balance text-red-400"
                    >
                        {$t("usernameNotValid")}
                    </h3>
                {/if}

                <input
                        bind:value={password}
                        class={!isPasswordValid && isFormSubmitted
            ? "rounded-md bg-red-400/5 p-2 text-red-400 outline outline-[1.5px] outline-red-400/10 transition-all placeholder:text-red-400/50 focus:outline-red-400/20"
            : "rounded-md bg-white/5 p-2 outline outline-[1.5px] outline-white/10 transition-all placeholder:text-white/50 focus:outline-white/20"}
                        placeholder={$t("password")}
                        type="password"
                />
                {#if !isPasswordValid && isFormSubmitted}
                    <h3
                            in:slide={{ duration: 300, easing: quintOut }}
                            class="text-balance text-red-400"
                    >
                        {$t("passwordNotValid")}
                    </h3>
                {/if}
                <button
                        on:click={login}
                        class={isLoading
            ? "pointer-events-none flex items-center justify-center gap-2 rounded-md bg-main p-2 opacity-50"
            : "flex items-center justify-center gap-2 rounded-md bg-main p-2 transition hover:bg-main/80"}
                >
                    {#if isLoading}
                        {$t("loggingIn")}
                        <Icon
                                class="flex-shrink-0 animate-spin text-base"
                                icon="fluent:spinner-ios-16-regular"
                        />
                    {:else}
                        {$t("login")}
                        <Icon class="flex-shrink-0 text-base" icon="ph:arrow-right" />
                    {/if}
                </button>
            </form>
            <button
                    on:click={() => navigate("/")}
                    class="mx-auto w-fit text-white/50"
            >
                {$t("alreadyLogin")}
                <span class="text-white underline transition hover:text-white/80"
                >{$t("myCourses")}</span
                >
            </button>
        </div>
    {/if}
    <p class="text-balance text-center text-white/50">
        Copyright © {new Date().getFullYear()}
        {name}
    </p>
</main>
